//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ado_Mudel_projekt_gluhhov
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Kutsekool_mudelContainer : DbContext
    {
        public Kutsekool_mudelContainer()
            : base("name=Kutsekool_mudelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Opilane> OpilaneSet { get; set; }
        public virtual DbSet<Ryhm> RyhmSet { get; set; }
    }
}
